import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import Button from '@mui/material/Button';
import ZoomInIcon from '@mui/icons-material/ZoomIn'; // Zoom icon from Material-UI
const OffplanCard = ({ property }) => {
    const { id, image, AtttributePropertyDetails, adTitle, DetailUrl, CommunityTitle, bgImage, developer_name, p_o_r, PriceTitleDetail, } = property;
    const baseUrl = window.location.origin;
    return (_jsx("div", { className: "col-lg-4 main-li", children: _jsxs("article", { className: "d-flex flex-column", children: [_jsxs("div", { className: "post-img lozad", style: { backgroundImage: `url('${image}')` }, children: [_jsx("span", { className: "dev_logo d-logo-s", title: developer_name, children: _jsx("img", { src: bgImage, alt: developer_name }) }), _jsx("ul", { className: "attrribute-ul hide d-none", children: _jsx("li", { children: AtttributePropertyDetails }) }), _jsx(NavLink, { to: `${baseUrl}${DetailUrl}`, className: "view-link-offplan", children: _jsx(Button, { variant: "contained", color: "primary", startIcon: _jsx(ZoomInIcon, {}), children: "View" }) })] }), _jsxs("div", { className: "contentcls", children: [_jsx("div", { className: "row", children: _jsxs("div", { className: "col-sm-12", children: [_jsx("div", { className: "row mt5 mb5 spl-margin-list ", children: _jsxs("div", { className: "col-sm-12 locpointer-detail flex-1", children: [_jsx("img", { src: "/img/placeholder.png", alt: "", className: "locpointer" }), CommunityTitle] }) }), _jsxs("h2", { className: "title sp-pr-ce-detail", children: [_jsx(NavLink, { to: `${baseUrl}${DetailUrl}`, children: adTitle }), _jsxs("div", { className: "price-text at-latest  flex-1", children: [p_o_r !== '1' && (_jsx("span", { className: "startingfrom", children: "Starting From" })), _jsx("div", { className: "white-space-nowrap", dangerouslySetInnerHTML: { __html: PriceTitleDetail } })] })] })] }) }), _jsx("div", { className: "row", children: _jsx("div", { className: "col-sm-4", style: { display: 'none', alignItems: 'center', justifyContent: 'center' }, children: _jsx("div", { className: "read-more w-100 align-center", style: { justifyContent: 'flex-end', display: 'flex' }, children: _jsx(NavLink, { to: `${baseUrl}${DetailUrl}`, children: "View Details" }) }) }) })] })] }) }, `${id}-index`));
};
export default OffplanCard;
