import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const LoadingDetail = () => {
    return (_jsx("div", { children: _jsx("div", { id: "pagepiling", className: "new-frmat", children: _jsx("div", { className: "offplan-head-section", children: _jsx("div", { className: "banner ", style: {
                        backgroundSize: "cover",
                        backgroundPosition: "center center",
                        backgroundRepeat: "no-repeat"
                    }, children: _jsx("div", { id: "img", className: "register_form_container", children: _jsx("div", { className: "align-frm", children: _jsx("div", { className: "align-frm-inner", children: _jsxs("div", { className: "register_form no-label fullwidthforms hidden-message less-opacity", children: [_jsx("h6", { children: "Register your interest" }), _jsxs("form", { className: "form bottom_leadContact leadContact phs", children: [_jsx("input", { type: "hidden", name: "ad_id", value: "1595" }), _jsx("div", { className: "pure-control-group form-icon form-icon-person less-opacity", children: _jsx("input", { className: "pure-input-1", placeholder: "Name", name: "name", type: "text" }) }), _jsx("div", { className: "pure-control-group form-icon form-icon-mail less-opacity", children: _jsx("input", { className: "pure-input-1 skeleton-item", placeholder: "Email", name: "email", type: "email", disabled: true }) }), _jsx("div", { className: "pure-control-group form-icon form-icon-mobile less-opacity", children: _jsx("input", { className: "pure-input-1", placeholder: "Phone", name: "phone", type: "text" }) }), _jsx("div", { className: "pure-control-group hide d-none", children: _jsx("textarea", { className: "pure-input-1", placeholder: "Message", name: "message" }) }), _jsx("button", { disabled: true, className: "primary_btn hover-pbg mt0 less-opacity", children: "Submit" }), _jsxs("p", { className: "terms-privacy", children: ["By clicking Submit, you agree to our", " ", _jsx("a", { href: "#nogo", children: "Terms" }), " &", " ", _jsx("a", { href: "#nogo", children: "Privacy Policy." })] })] }), _jsxs("div", { className: "offplan-card-agent pb0", children: [_jsxs("div", { className: "agent_name_img", children: [_jsx("img", { src: "/img/user.png", alt: "Agent" }), _jsx("h6", { className: "agent-contact skeleton-item", children: "\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0" })] }), _jsx("div", { className: "mail_agent", children: _jsxs("div", { className: "agent_contact-offplan", children: [_jsxs("a", { target: "_blank", rel: "noopener noreferrer", href: "#", children: [_jsx("img", { src: "/img/whats.svg", alt: "" }), _jsx("span", { className: "social_name text-social skeleton-item", children: "WhatsApp" })] }), _jsxs("a", { href: "tel:+971501950988", className: "phone", children: [_jsx("img", { src: "/img/call.svg", alt: "" }), _jsx("span", { className: "social_name skeleton-item", children: "Phone" })] })] }) })] })] }) }) }) }) }) }) }) }));
};
export default LoadingDetail;
